### ISSUE TITLE
Dunno

### ISSUE THREAD

**Issue by German998** [alcatrazEscapee/no-tree-punching#103]
[idk.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/3855112/idk.txt)

freezes the game, its just random, i was inside my hosue when it happnd

**Comment by alcatrazEscapee** [comment]
This has nothing to do with No Tree Punching. From the log, it looks like you've removed NTP from the game, potentially breaking any other scripts using it (I'm guessing RLCraft). Reading the crash log, it's likely due to some ASM from wolf armor, as I don't know what else would force a bytecode dump.

**Comment by German998** [comment]
oh ok and yeah i did that, ty vm
