### ISSUE TITLE
Tags always_breakable and always_drops should reference the leaves tag instead of individual leaves

### ISSUE THREAD

**Issue by G-Stav** [alcatrazEscapee/no-tree-punching#131]
I noticed that leaves/logs don't have the tags "minecraft:leaves" or "minecraft:logs". Since they're not meant to be obtainable even via silk touch they shouldn't need it I suppose, but I'm guessing it's part of the reason they're not harvestable. No Tree Punching doesn't realize that they're leaf blocks and therefore it's not a block you're allowed to punch to harvest.

I tried adding the leaves tag via crafttweaker to see if it would fix it, but apparently not.

Attached are some screenshots displaying the issue.

![2020-10-01_00 19 26](https://user-images.githubusercontent.com/18726116/94745411-f2d6f800-037a-11eb-96ce-348dff6b0885.png)
![2020-10-01_00 19 27](https://user-images.githubusercontent.com/18726116/94745414-f4082500-037a-11eb-838c-c8c74e2101e7.png)
![2020-10-01_00 19 29](https://user-images.githubusercontent.com/18726116/94745418-f4082500-037a-11eb-9f07-2aa2058faf55.png)
![2020-10-01_00 19 30](https://user-images.githubusercontent.com/18726116/94745421-f4a0bb80-037a-11eb-9884-8ed39655579f.png)

**Comment by alcatrazEscapee** [comment]
1. This is entirely possible within No Tree Punching's set of configuration features for block breaking. The reason leaves are always breakable is because they're added to the `always_breakable` and `always_drops` tags. [See the wiki for details](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking).
2. In this case, NTP should just reference the leaves tag for future mod compatibility.
