### ISSUE TITLE
Cant find any items of No Tree Punching

### ISSUE THREAD

**Issue by DarkRedRat** [alcatrazEscapee/no-tree-punching#140]
So, i played minecraft with my selfmade modpack but i couldn't find any pebbles or make flint shards. I used creative mode and JEI but the items are not there

**Comment by alcatrazEscapee** [comment]
Given the total lack of any versions or other relevant information provided, I shall explain for the latest (1.16) version:

- Pebbles do not spawn in newer versions (1.16) yet due to world gen not being implemented.
- Flint shards are made by [Knapping](https://github.com/alcatrazEscapee/no-tree-punching/wiki/Knapping).
