### ISSUE TITLE
Minecraft crashes when I use NoTreePunching

### ISSUE THREAD

**Issue by BlackRagnarok** [alcatrazEscapee/no-tree-punching#141]
Hello, these days I have been trying to create a server with this mod, but it would not let me enter, I checked that everything was correct, I tried it in a singleplayer world and when I entered a world, minecraft crashed, on the server everything is fine, but I get stuck on the "connecting to the server" screen, and if I press the cancel button, it crashes, I had used this mod before in the same version (1.16.3) and if it worked, also all my friends if it works and they can enter the server without problems :/
PD: if something is misspelled, its cause i speak spanish and i used google Translator

**Comment by alcatrazEscapee** [comment]
If there is a crash, you should provide a crash log. This issue is the equivalent of telling the mechanic "hey my car doesn't work" and expecting them to be able to magically diagnose, figure out, and solve your problem *all without ever seeing or touching your car*.

So yeah, logs please if you want any hope of solving this.

**Comment by alcatrazEscapee** [comment]
If there's no other information here, there's literally nothing I can do.
