### ISSUE TITLE
Ability to break logs placed by player

### ISSUE THREAD

**Issue by fleetag** [alcatrazEscapee/no-tree-punching#148]
I find it very odd that whenever I try to replace the logs in of my builds, it never gives them back unless I use an axe. There should be an option where although the player can't break naturally generated logs (trees for an example), they are able to break and receive player placed logs.

**Comment by alcatrazEscapee** [comment]
No. There's no reason for this, nor is there a feasible way of marking every single player-placed block in the world. 

In vanilla, you cannot place cobblestone and break it with your bare hand just because it is "player placed". There is no reason any other blocks should be applied differently. If you want to exclude specific blocks from this "always requiring tools" behavior, there are [customization options](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration) available for that.
