### ISSUE TITLE
doInstantBreakBlocksRequireTool option not working

### ISSUE THREAD

**Issue by FastBoye127** [alcatrazEscapee/no-tree-punching#153]
I've changed doInstantBreakBlocksRequireTool to false and had no results, I still can't get drops from flowers, mushrooms, etc.

**Comment by alcatrazEscapee** [comment]
Everything you just described (admittedly very briefly) sounds like intentional behavior

- That option is by default false, and when true, prevents you from being *able* to break blocks that would otherwise instant break. It has nothing to do with drops.
- Many vanilla plant type blocks actually have an axe as their primary tool. This is a rather unexpected result of the way vanilla handles harvest tools. It's something I'm aware of as an area to improve, but not quite sure how to go about it without explicitly just changing vanilla behavior.
