### ISSUE TITLE
Add modded wood logs

### ISSUE THREAD

**Issue by YejiYeah** [alcatrazEscapee/no-tree-punching#163]
Hi,

The mod is amazing, however I noticed that modded wood logs are not detected by the mod and I can break them by hand, also I dont need the saw to convert them into sticks or planks.

Forge 1.16.5.36.1.1
No tree punching 1.16.5-4.1.2

Thank you,
Kind regards,
Sarah

**Comment by alcatrazEscapee** [comment]
So

- Due to the way recipes work in >1.12 this can no longer be an automatic process. If other mods are specified to work with NTP, they have to be explicitly added.
- You can add + remove the required recipes, such as removing log -> plank ones and adding the saw/axe versions yourself, with a datapack. See #127 where I go into a bit more detail.
- Re: "modded wood logs are not detected by the mod"
  - What mod? This matters as it's likely something said mod did incorrectly, i.e. not giving their logs a harvest tool.
  - If a mod makes blocks able to be broken by hand (i.e. not giving them a harvest tool), and makes them out of a non-common material (i.e. so NTP can't detect if it's wood or not), there's nothing I can do. However if you give the name of said mod and what blocks are, I may be able to take a look into why it's occurring and actually point towards an issue resolution.
