### ISSUE TITLE
Conflicting harvest conditions, can't harvest vines

### ISSUE THREAD

**Issue by V972** [alcatrazEscapee/no-tree-punching#167]
Forge 36.1.4 for Minecraft 1.16.5
I'm using the default config and latest version available on CurseForge as of time of writing this.

HWYLA shows appropriate tool as Axe, but neither Axes/Mattoks nor Shears dropped the vines.
I couldn't find the way to change what blocks require what tool(s) in the config OR wiki.

**Comment by alcatrazEscapee** [comment]
- Have you tried a sword / knife?
- Shears seem to be funky last time I had checked, I will look into them (I wouldn't be surprised if #156 is the same issue)

> I couldn't find the way to change what blocks require what tool(s)

You can specify blocks to ignore harvestability checks all together (the tags mentioned in the wiki). Changing specific tools is not doable unfortunately, not without some quite invasive rework of the vanilla/forge functionality underneath - it is the same root issue as #157.

**Comment by alcatrazEscapee** [comment]
Alright I think I see what's going on here.

- Vines don't declare a tool in vanilla, but declare the plant material
- Axes are coded to break plant materials at faster than default speeds
- Because vines don't declare a tool, Forge checks their material, and assumes that all plant material blocks are an axe tool type. (This happens with a lot of vanilla plants)
- *Unlike* most vanilla plants, vines have a specific loot table which is hardcoded to drop items when using shears, and only shears (using the `minecraft:match_tool` condition).
