### ISSUE TITLE
Stone tools still able to be crafted (with Quark)

### ISSUE THREAD

**Issue by van-riper** [alcatrazEscapee/no-tree-punching#173]
I have encountered a bug where the crafting recipes are still available for the stone tools. No apparent errors that I can see.

Modlist:
abnormals_core-1.16.5-3.1.1.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
Aquaculture-1.16.5-2.1.18.jar
astikorcarts-1.16.5-1.1.1.jar
AutoRegLib-1.6-47.jar
BetterCaves-Forge-1.16.4-1.1.1.jar
BetterMineshafts-Forge-1.16.4-2.0.3.jar
BiomesOPlenty-1.16.5-13.1.0.465-universal.jar
Bookshelf-1.16.5-10.0.7.jar
Clumps-6.0.0.22.jar
collective-1.16.5-2.26.jar
comforts-forge-1.16.4-4.0.1.0.jar
CraftableHorseArmour-1.16.X-1.4.0.jar
create-mc1.16.5_v0.3.1c.jar
cuneiform-1.16.3-1.2.4.1.jar
DoggyTalents-1.16.5-2.0.1.4.jar
endergetic-1.16.4-3.0.0.jar
gravestone-1.16.5-1.0.4.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
infernal-expansion-forge-1.3.jar
itemzoom-1.16.4-2.3.0.jar
jei-1.16.5-7.6.4.90 12.50.04 PM.jar
jei-professions-1.0.0-1.16.4.jar
JEIEnchantmentInfo-1.16.4-1.2.1.jar
jeiintegration_1.16.5-7.0.1.15.jar
journeymap-1.16.5-5.7.1.jar
More Totem Effects 1.16.5  v1.4.jar
MouseTweaks-2.14-mc1.16.2.jar
notreepunching-forge-1.16.5-4.1.3.jar
Quark-r2.4-311.jar
QuarkOddities-1.16.3.jar
QuarkOPlenty-1.16.5-1.2.1.jar
repurposed_structures-1.16.5-2.6.6-forge.jar
SereneSeasons-1.16.5-4.0.1.91-universal.jar
spiders-2.0-1.16.4-1.0.4.jar
StorageDrawers-1.16.3-8.2.2.jar
swingthroughgrass-1.16.4-1.5.3.jar
terraincognita-1.16.3-1.6.4.2.jar
Tips-1.16.5-4.0.7.jar
travelers_index-1.16.4-1.0.2.jar
villagernames_1.16.5-2.9.jar
YungsApi-1.16.4-Forge-6.jar

**Comment by alcatrazEscapee** [comment]
Find out what mod is overriding the recipe then. As that's the exact same thing NTP does, and whichever mod loads their data last will "win".

At a hunch: try quark.

**Comment by van-riper** [comment]
Yes, I just disabled quark (along with quarksoplenty and quarkoddities), and that fixed it.

**Comment by alcatrazEscapee** [comment]
So

- The stone tools I believe are caused by quark's "better stone tools" option. This is from [these recipes](https://github.com/Vazkii/Quark/blob/master/src/main/resources/data/minecraft/recipes/stone_pickaxe.json).
- Quark does something very odd here, in that they replace the `minecraft:stone_tool_materials` tag in said recipe with `minecraft:cobblestone`, in such a way that means the recipe gets forced on (as NTP data loads before quark by default).
- *I think* they should fix this and just add the cobblestone tag to the stone tool materials, then we wouldn't have this issue.
- I could also (I believe) put a dependency to load NTP's resources after quark. But this is rather awkward and I'd rather avoid this if possible (as it solves *this specific issue* and no others). Which is probably what I'll end up doing because I don't believe quark is going to change this (based on a prior conversation about this exact recipe I just pulled up).

In general,
- you can make a [datapack](https://minecraft.fandom.com/wiki/Data_Pack) (even copying how [the NTP recipes work](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.16.x/src/main/resources/data/minecraft/recipes/wooden_pickaxe.json)), which disable wooden and stone tools. Then load this after both mods, and choose whatever combination of NTP and quark features you would like.

**Comment by van-riper** [comment]
Okay, I will make a ticket on quark's github and bring this up. I'll tag you in it as well so you can get notifs. I just fear that they changed that tag for a specific reason that they will not be willing to change. Perhaps a compatiblity patch would work, but I'm not a modder and I don't know the logistics of that.

Anyways, I'll make a ticket and hopefully that'll change this predicament.

**Comment by van-riper** [comment]
[just made the ticket](https://github.com/Vazkii/Quark/issues/3169)

**Comment by alcatrazEscapee** [comment]
Alright, so in conclusion, I am not going to specifically override Quark's recipes. Both mods make a modification to the same recipes, Quark does so in a bit of a painful way (but their options are limited by the non-existence of conditional tag entries). So you can either write the datapack to resolve conflicts, or fix as mentioned above.
