### ISSUE TITLE
Plz add wooden tools but as "train tools" idk, but add them...

### ISSUE THREAD

**Issue by Landrozaum** [alcatrazEscapee/no-tree-punching#178]
I'm playing with some mods and one of them need the wooden shovel as the wooden spoon, and i can't craft it.
The mod that i are playing is Farmer's Delight : https://www.curseforge.com/minecraft/mc-mods/farmers-delight

Can you bring back the wooden tools, or make compatibility with this mod?

**Comment by alcatrazEscapee** [comment]
No, I am not going to add back tools that would otherwise *make the entire mod obselete.* That would be silly.

Feel free to add the recipes back, or more wisely, edit the recipes of farmers delight, in order to not require such items. You can do so with a [Datapack](https://minecraft.fandom.com/wiki/Data_Pack)
