### ISSUE TITLE
Yes, that's intentional. See: vanilla.

### ISSUE THREAD

**Issue by Suxtrer** [alcatrazEscapee/no-tree-punching#183]
Yes, that's intentional. See: vanilla.

If you are trying to create wood planks, use the crafting recipe. See in either the recipe book, or using JEI (the mod).

_Originally posted by @alcatrazEscapee in https://github.com/alcatrazEscapee/no-tree-punching/issues/181#issuecomment-856224726_

why you don't moddify the mod for make planks with the stripped wood?

**Comment by alcatrazEscapee** [comment]
There was no need to reference this is another issue.

I didn't want to create a different way to create stripped wood. Nor did I want to rewrite all of wood stripping mechanics, because both in Vanilla and Forge, there's a baked in assumption that stripping will produce *blocks* not items. And, crafting recipes, while functionally the same, are more transparent as they can be seen in either the recipe book or JEI.
