### ISSUE TITLE
Iron axe disappearing when creating wooden planks.

### ISSUE THREAD

**Issue by UnderscoreX5** [alcatrazEscapee/no-tree-punching#184]
When crafting wooden planks the iron axe disappears and the result it just 2 wood. This is certainly a bug and it's game-breaking.

**Comment by alcatrazEscapee** [comment]
Well, it is a bug yes, it is not exactly game breaking. Seeing as up until the most recent version, you were unable to craft planks at all with an axe (you should use a saw).

That said... this is reminding me why I didn't make axes the crafting tool of choice in the first place, and why saws exist - due to container item shenagains.
