### ISSUE TITLE
Modded Logs be stealing my tools.

### ISSUE THREAD

**Issue by FionaDanger** [alcatrazEscapee/no-tree-punching#196]
Vanilla logs being axed and sawed? takes a bit of durability.

Modded logs being axed and sawed? One craft and I get 2/4 planks and no tool. 

Tested with Biomes You'll Go and Biomes O' Plenty logs with the latest version of this mod, their mods, and forge.

**Comment by alcatrazEscapee** [comment]
BYG recipes should be fixed as of eb1f1c4046c86b8fdaf8c4c691d4d52ef015e80d 
NTP does not have any compat recipes for BoP, so that would be a question for the pack maker (as they'd be the ones adding / changing those recipes). A recent breakage would likely be due to a change I had to make in order to support axes in these recipes (#184).
