### ISSUE TITLE
Dynamic Trees Compatibility

### ISSUE THREAD

**Issue by OceanSnipe17** [alcatrazEscapee/no-tree-punching#198]
With dynamic trees I cannot break any branches with this mod. I can still break leaves to get sticks but it would be nice to be able to break branches for sticks while still needing tools to cut the logs.

**Comment by AsterionXeity** [comment]
The logs also don't turn into wooden plants how much i spam my right click with an flint axe, vanilla and modded.

**Comment by OceanSnipe17** [comment]
@ZeldrexK0DE have you tried the altered crafting recipe? I believe it's an axe over a log. My only thought.

**Comment by AsterionXeity** [comment]
> @ZeldrexK0DE have you tried the altered crafting recipe? I believe it's an axe over a log. My only thought.

There was only one recipe. The string, flint and a stick. I just disabled NTP for now and it seems to work fine though have to make the planks in a crafting table instead of it giving me them after "chopping" them.

**Comment by alcatrazEscapee** [comment]
> With dynamic trees I cannot break any branches with this mod

Yes because the titular feature is that you cannot break blocks with the incorrect tool. If you want to change this see the [wiki](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration) for configuration options

> The logs also don't turn into wooden plants how much i spam my right click with an flint axe, vanilla and modded.

1. don't spam one issue with your unrelated problems.
2. you're trying to use a 1.12 mechanic in >1.12 versions of NTP which don't have this *because wood stripping exists*. There is indeed a crafting recipe.

> There was only one recipe.
[There's a dam sight more than that](https://github.com/alcatrazEscapee/no-tree-punching/tree/1.16.x/src/main/resources/data/notreepunching/recipes)
