### ISSUE TITLE
Silent's gear saw and axes compatibility

### ISSUE THREAD

**Issue by YejiYeah** [alcatrazEscapee/no-tree-punching#201]
Hello, 

I have been trying the mod Silent's gear but the tools seems to be not comtatible to craft planks and sticks, is something you could fix?, or is this related to Silent's gear modder?

Thank you for fixing the problem with the BYG wood!, it was my birthday present literally!

Best regards!
Sarah

**Comment by alcatrazEscapee** [comment]
>  the tools seems to be not comtatible to craft planks and sticks

Add their tools to the [tag](https://github.com/alcatrazEscapee/no-tree-punching/blob/eb1f1c4046c86b8fdaf8c4c691d4d52ef015e80d/src/main/resources/data/notreepunching/recipes/sticks_from_logs_with_saw.json#L11) which is used then with a datapack.

Yes, it is something I could technically fix with an optional datapack. Except the likelyhood of that happening is low due to my own lack of time. But it is entirely within the reach of pack makers.
