### ISSUE TITLE
soul campfire should be made with a fire starter

### ISSUE THREAD

**Issue by freyebeans** [alcatrazEscapee/no-tree-punching#213]
the soul campfire should also be made with the fire starter and possibly also have compatibility with the ender campfire from the endergetic expansion

**Comment by Gunner76th** [comment]
https://github.com/alcatrazEscapee/no-tree-punching/commit/46682d0a26ece9a408e79db560a208d8cb405bde

Looking a the note for this commit it would appear that the addition of the config option to enable/disable the recipe for each of the campfires was overlooked. 

![image](https://user-images.githubusercontent.com/5566872/155138979-c8fc8b8c-0f80-4282-9090-15a1bd615d49.png)

This has broken crafting recipes for https://www.curseforge.com/minecraft/modpacks/engineers-life-2 in which we were using the soul camp fire as a crafting ingredient for several other items. Will the config option to enable/disable the removal of the crafting recipe for the camp fire and soul camp fire be added into the next update since it was missed in 4.3.0?

**Comment by Gunner76th** [comment]
To clarify, some mods as well as modpacks depend on the vanilla campfire or soul campfire recipe for the crafting of other items. by removing those recipes without either the option to add them back in through the config, or leaving the recipe in game but making the crafted item not placeable has caused those mods and modpacks to become broken. Please consider either adding a config option to restore the recipe if the config is set to false for the campfires to be creatable with the fire starter, or have it leave the recipe in game but change it to a non-placeable item.

**Comment by alcatrazEscapee** [comment]
>  the addition of the config option to enable/disable the recipe for each of the campfires was overlooked.

No, it wasn't. Modification of recipes is done via datapacks, I'm not going to add a config option for something that's already completely possible to do.
