### ISSUE TITLE
Removing sticks from loot drops

### ISSUE THREAD

**Issue by WolfieWaffle** [alcatrazEscapee/no-tree-punching#223]
Someone had an issue with my mod not dropping sticks from burnt torches, and they discovered it was most likely because this mod was removing stick drops from all loot tables. I would suggest a better method of preventing sticks from dropping from leaves, since this could cause issues with other mods in the future as well.

**Comment by alcatrazEscapee** [comment]
> likely because this mod was removing stick drops from all loot tables.

Okay, first off, no. I don't touch loot tables. I touch harvest checks, all of which can be configured for certain blocks to be bypassed. I simply enforce that blocks have to be mined, and drop, when using the correct tool.

>  a better method of preventing sticks from dropping from leaves

I literally don't modify sticks dropping from leaves.... leaves are [specifically whitelisted](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.18.x/Common/src/main/resources/data/notreepunching/tags/blocks/always_drops.json) to always drop their contents. Preventing sticks dropping from leaves would quite literally make this mod unusable, since it relies on them to obtain tools.

So, I don't see what your issue is, because you're making up features this mod does not have. If you have an actual compat issue you want to look into I'd be happy to entertain it.

**Comment by WolfieWaffle** [comment]
ok, I will tell him it is probably another mod then. I didn't install to check, he just told me that when he installed your mod the sticks stopped dropping, no need to be rude.
