### ISSUE TITLE
Torches don't drop if you directly break them

### ISSUE THREAD

**Issue by asikwus** [alcatrazEscapee/no-tree-punching#227]
Felt most likely to be a bug, since they drop if you break the block they're attached to.

Setup:
MC 1.18.2
MC Forge 40.1.0
notreepunching-forge-1.18.2-5.0.3

**Comment by alcatrazEscapee** [comment]
Under the default configuration options:

- Torches, as a block that breaks instantly, are always breakable.
- In order to get their item to drop, they must be harvested with the correct tool, which for torches, is inferred to be a pickaxe.
- They are not specifically whitelisted to ignore either of these rules by default.
- Breaking when unsupported is a separate behavior than when broken by a player, and thus is unaffected by NTP's harvestability rules.

All that said, this is working as intended.

**Comment by asikwus** [comment]
Ah alright. I guess I'll just put doInstantBreakBlocksDropWithoutCorrectTool to true, or as what I get by "They are not specifically whitelisted to ignore either of these rules by default.", there is a way to whitelist them from this? (can't seem to find that in the config)

**Comment by alcatrazEscapee** [comment]
Yes with a tag, noted in the [wiki](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking)
