### ISSUE TITLE
cannot craft cooking pot from farmer's delight

### ISSUE THREAD

**Issue by Skellykenz** [alcatrazEscapee/no-tree-punching#297]
unable to craft wooden shovel, a component of cooking pots in farmer's delight

**Comment by Skellykenz** [comment]
neither can I craft the stove

**Comment by ginsm** [comment]
You can fix this via a datapack by changing the cooking pot recipe ([forge](https://github.com/vectorwing/FarmersDelight/blob/1.19/src/generated/resources/data/farmersdelight/recipes/cooking_pot.json), [fabric](https://github.com/MehVahdJukaar/FarmersDelight/blob/1.20/src/generated/resources/data/farmersdelight/recipes/cooking_pot.json)). I changed it to a stick personally. I'll attach the one I created to this comment but you may need to change the `pack_format` value in `pack.mcmeta` if you're not on `1.20.1`. Here's the different pack format values for each version: https://minecraft.fandom.com/wiki/Data_pack#Pack_format.

[NTP_FDCookingPot_Fix.zip](https://github.com/user-attachments/files/15911532/NTP_FDCookingPot_Fix.zip)

**Comment by Skellykenz** [comment]
Thank you so much my data pack didn’t work so this is great tysm

**Comment by ginsm** [comment]
No problem! But I didn't realize that the stove couldn't be crafted either so that datapack only works for the cooking pot. Here's the updated one including the stove:

[NTP_FD_Compat.zip](https://github.com/user-attachments/files/15920254/NTP_FD_Compat.zip)

I replaced the Campfire with a Flint and Steel in the crafting recipe for the stove.
