### ISSUE TITLE
[Suggestion] Config option and features

### ISSUE THREAD

**Issue by Priderino** [alcatrazEscapee/no-tree-punching#30]
[Config]:
It would be nice to have a way to configure what the loose rocks will drop.
Configure how many logs you can put on a log pile, in my opinion 4 stacks is too much.
EDIT: Also a way to config what drops when you cut tall grass with a knife. 

[Features]: 
Some kind of primitive Coke Oven to get better fuel is a good option, but not greatly needed.
Having a way to store ingots on a pile, just like the logs.
An early game storage, like Clay Vessels that you can cook on the fire pit, or maybe on the forge.
Adding a way to make plates early game, like a Stone Anvil and adding plates for each ingot (including vanilla ones).

**Comment by alcatrazEscapee** [comment]
1. So the log pile should only hold 16 logs, 4 per slot, that is a bug, should be fixed in 1.4.1d. Config option for that is problematic since the charcoal pit can only produce so much charcoal per log pile.

2. What drops do you want to add to knife grass breaking?

3. If you want a coke oven I would recommend something like Immersive Engineering. It seems outside the scope of NTP.

4. That sounds good. [This](https://wiki.terrafirmacraft.com/Ingot#Ingot_Piles) is what I would base it off of, but the problem here would be that ingots are storable in typical chests. Is there a mod that adds carry weight / item size like TFC from 1.7.10?

5. For early game storage solutions I would recommend Immersive Craft. Although this is a possibility.

6. Plates are outside the scope of NTP, as there is nothing in NTP that would be crafted with them. I want to limit the number of "features that are useless by themselves" as much as possible.

**Comment by Priderino** [comment]
1. I found it weird that i put 2 stacks of logs and got too little charcoal, was ready to report it as a bug.

2. PrimalCore's thatch, since in my pack wool is gated behind a Tailor's Worktable, i would use it to mostly craft Primal Tech's "Bed of Straw and Leaves".

3. I'm ok without coke ovens.

4. There's PlayerWeight, you can configure weight and stack size. Also you can stack ingots like TFC with Charset Immersion, but it would be nice to have it as a feature of NTP.

5. I'm not a fan of Immersive Craft, i find it too weird to use, a simple clay vessel with a 3x3 would be great for early game, it could work like a backpack, or like a shulker box, and it kinda fits the mod.

6. Yeah, that's what I thought.


I'm making a harsh survival, low tech, TFC inspired modpack.

**Comment by alcatrazEscapee** [comment]
2. A Crafttweaker method is added in 1.4.2

**Comment by alcatrazEscapee** [comment]
Re 5: Added pottery (with a 3x3 block inventory, and a 2x2 item based inventory) in 1.4.3beta1

**Comment by Priderino** [comment]
Just checked your pottery update, it's fantastic, you did what I suggested, but made it 10 times better.
As soon as you add a way to change what the loose rocks drops, your mod will be one of my favorites.
Keep up the good work :D

**Comment by alcatrazEscapee** [comment]
I've thought about adding a config for rock drops, and I've decided not to. 
1. They drop loose rock items, because that item will place them. Changing the drop would also involved changing every item interaction with those items, and potentially require disabling rock items, which would cause a whole load of progression issues, and
2. This is easily achievable with a third party such as [Block Drops Tweaker](https://minecraft.curseforge.com/projects/block-drops-tweaker)

And Re: logs in clay vessels, this is something I think deserves its own mod. Similar to the TFC-esque method of assigning each item a weight / size, and controlling inventory use / stacksize through that. Also, logs can be stored in chests. Or any other container that isn't explicitly forbidding them. Log piles aren't meant to force the player to use them as their primary storage of logs. They are used in charcoal pits or for aesthetic purposes. It would be strange to force the player to not be able to store _only_ logs in _only_ clay vessels.

Ingot piles I may get around to at some point, or that might become its own mod. Closing this issue because its getting to complicated. If you have any other suggestions just open another ticket.
